# Generated by Django 3.0.4 on 2020-03-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
