# Generated by Django 3.0.4 on 2020-03-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
