# Generated by Django 3.0.4 on 2020-03-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
