# Generated by Django 3.0.4 on 2020-03-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default=None, max_length=200, null=True),
        ),
    ]
